<?php

/**
 * @file
 * Contains firebase_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_help().
 */
function firebase_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the firebase_ui module.
    case 'help.page.firebase_ui':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements entity_bundle_field_info_alter().
 */
function firebase_ui_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'user') {
    if (!empty($fields['field_user_token_devices'])) {
      $fields['field_user_token_devices']->addConstraint('UserTokenConstraint');
    }
  }
}
